export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_SEARCH_MODAL = "OPEN_SEARCH_MODAL";
export const CLOSE_SEARCH_MODAL = "CLOSE_SEARCH_MODAL";

export const OPEN_CREATE_ENTITY_MODAL = "OPEN_CREATE_ENTITY_MODAL";
export const CLOSE_CREATE_ENTITY_MODAL = "CLOSE_CREATE_ENTITY_MODAL";
export const SET_CREATE_ENTITY_TYPE = "SET_CREATE_ENTITY_TYPE";

export const OPEN_APPOINTMENT_MODAL = "OPEN_APPOINTMENT_MODAL";
export const CLOSE_APPOINTMENT_MODAL = "CLOSE_APPOINTMENT_MODAL";

export const OPEN_ALERT = "OPEN_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const SET_USER = 'SET_USER';